#ifndef GPIO_H
#define GPIO_H

#include <avr/io.h>

//Macros to read/write IO by single names instead of REG+BIT everywhere

#define IO_OUTPUT(port) _IO_OUTPUT(port)
#define _IO_OUTPUT(port) do { \
    _IO_DDR_REG_ ## port |= _BV(_IO_BIT_ ## port); \
} while(0)
#define IO_INPUT(port) _IO_INPUT(port)
#define _IO_INPUT(port) do { \
    _IO_DDR_REG_ ## port &=~_BV(_IO_BIT_ ## port); \
} while(0)
#define IO_WRITE(port, value) _IO_WRITE(port, value)
#define _IO_WRITE(port, value) do { \
    if (value) \
        _IO_PORT_REG_ ## port |= _BV(_IO_BIT_ ## port); \
    else \
        _IO_PORT_REG_ ## port &=~_BV(_IO_BIT_ ## port); \
} while(0)
#define IO_READ(port) _IO_READ(port)
#define _IO_READ(port) ((_IO_PIN_REG_ ## port) & _BV(_IO_BIT_ ## port))

#define _IO_PORT_REG_A0 PORTA
#define _IO_DDR_REG_A0  DDRA
#define _IO_PIN_REG_A0  PINA
#define _IO_BIT_A0      0
#define _IO_PORT_REG_A1 PORTA
#define _IO_DDR_REG_A1  DDRA
#define _IO_PIN_REG_A1  PINA
#define _IO_BIT_A1      1
#define _IO_PORT_REG_A2 PORTA
#define _IO_DDR_REG_A2  DDRA
#define _IO_PIN_REG_A2  PINA
#define _IO_BIT_A2      2
#define _IO_PORT_REG_A3 PORTA
#define _IO_DDR_REG_A3  DDRA
#define _IO_PIN_REG_A3  PINA
#define _IO_BIT_A3      3
#define _IO_PORT_REG_A4 PORTA
#define _IO_DDR_REG_A4  DDRA
#define _IO_PIN_REG_A4  PINA
#define _IO_BIT_A4      4
#define _IO_PORT_REG_A5 PORTA
#define _IO_DDR_REG_A5  DDRA
#define _IO_PIN_REG_A5  PINA
#define _IO_BIT_A5      5
#define _IO_PORT_REG_A6 PORTA
#define _IO_DDR_REG_A6  DDRA
#define _IO_PIN_REG_A6  PINA
#define _IO_BIT_A6      6
#define _IO_PORT_REG_A7 PORTA
#define _IO_DDR_REG_A7  DDRA
#define _IO_PIN_REG_A7  PINA
#define _IO_BIT_A7      7
#define _IO_PORT_REG_B0 PORTB
#define _IO_DDR_REG_B0  DDRB
#define _IO_PIN_REG_B0  PINB
#define _IO_BIT_B0      0
#define _IO_PORT_REG_B1 PORTB
#define _IO_DDR_REG_B1  DDRB
#define _IO_PIN_REG_B1  PINB
#define _IO_BIT_B1      1
#define _IO_PORT_REG_B2 PORTB
#define _IO_DDR_REG_B2  DDRB
#define _IO_PIN_REG_B2  PINB
#define _IO_BIT_B2      2
#define _IO_PORT_REG_B3 PORTB
#define _IO_DDR_REG_B3  DDRB
#define _IO_PIN_REG_B3  PINB
#define _IO_BIT_B3      3
#define _IO_PORT_REG_B4 PORTB
#define _IO_DDR_REG_B4  DDRB
#define _IO_PIN_REG_B4  PINB
#define _IO_BIT_B4      4
#define _IO_PORT_REG_B5 PORTB
#define _IO_DDR_REG_B5  DDRB
#define _IO_PIN_REG_B5  PINB
#define _IO_BIT_B5      5
#define _IO_PORT_REG_B6 PORTB
#define _IO_DDR_REG_B6  DDRB
#define _IO_PIN_REG_B6  PINB
#define _IO_BIT_B6      6
#define _IO_PORT_REG_B7 PORTB
#define _IO_DDR_REG_B7  DDRB
#define _IO_PIN_REG_B7  PINB
#define _IO_BIT_B7      7
#define _IO_PORT_REG_C0 PORTC
#define _IO_DDR_REG_C0  DDRC
#define _IO_PIN_REG_C0  PINC
#define _IO_BIT_C0      0
#define _IO_PORT_REG_C1 PORTC
#define _IO_DDR_REG_C1  DDRC
#define _IO_PIN_REG_C1  PINC
#define _IO_BIT_C1      1
#define _IO_PORT_REG_C2 PORTC
#define _IO_DDR_REG_C2  DDRC
#define _IO_PIN_REG_C2  PINC
#define _IO_BIT_C2      2
#define _IO_PORT_REG_C3 PORTC
#define _IO_DDR_REG_C3  DDRC
#define _IO_PIN_REG_C3  PINC
#define _IO_BIT_C3      3
#define _IO_PORT_REG_C4 PORTC
#define _IO_DDR_REG_C4  DDRC
#define _IO_PIN_REG_C4  PINC
#define _IO_BIT_C4      4
#define _IO_PORT_REG_C5 PORTC
#define _IO_DDR_REG_C5  DDRC
#define _IO_PIN_REG_C5  PINC
#define _IO_BIT_C5      5
#define _IO_PORT_REG_C6 PORTC
#define _IO_DDR_REG_C6  DDRC
#define _IO_PIN_REG_C6  PINC
#define _IO_BIT_C6      6
#define _IO_PORT_REG_C7 PORTC
#define _IO_DDR_REG_C7  DDRC
#define _IO_PIN_REG_C7  PINC
#define _IO_BIT_C7      7
#define _IO_PORT_REG_D0 PORTD
#define _IO_DDR_REG_D0  DDRD
#define _IO_PIN_REG_D0  PIND
#define _IO_BIT_D0      0
#define _IO_PORT_REG_D1 PORTD
#define _IO_DDR_REG_D1  DDRD
#define _IO_PIN_REG_D1  PIND
#define _IO_BIT_D1      1
#define _IO_PORT_REG_D2 PORTD
#define _IO_DDR_REG_D2  DDRD
#define _IO_PIN_REG_D2  PIND
#define _IO_BIT_D2      2
#define _IO_PORT_REG_D3 PORTD
#define _IO_DDR_REG_D3  DDRD
#define _IO_PIN_REG_D3  PIND
#define _IO_BIT_D3      3
#define _IO_PORT_REG_D4 PORTD
#define _IO_DDR_REG_D4  DDRD
#define _IO_PIN_REG_D4  PIND
#define _IO_BIT_D4      4
#define _IO_PORT_REG_D5 PORTD
#define _IO_DDR_REG_D5  DDRD
#define _IO_PIN_REG_D5  PIND
#define _IO_BIT_D5      5
#define _IO_PORT_REG_D6 PORTD
#define _IO_DDR_REG_D6  DDRD
#define _IO_PIN_REG_D6  PIND
#define _IO_BIT_D6      6
#define _IO_PORT_REG_D7 PORTD
#define _IO_DDR_REG_D7  DDRD
#define _IO_PIN_REG_D7  PIND
#define _IO_BIT_D7      7
#define _IO_PORT_REG_E0 PORTE
#define _IO_DDR_REG_E0  DDRE
#define _IO_PIN_REG_E0  PINE
#define _IO_BIT_E0      0
#define _IO_PORT_REG_E1 PORTE
#define _IO_DDR_REG_E1  DDRE
#define _IO_PIN_REG_E1  PINE
#define _IO_BIT_E1      1
#define _IO_PORT_REG_E2 PORTE
#define _IO_DDR_REG_E2  DDRE
#define _IO_PIN_REG_E2  PINE
#define _IO_BIT_E2      2
#define _IO_PORT_REG_E3 PORTE
#define _IO_DDR_REG_E3  DDRE
#define _IO_PIN_REG_E3  PINE
#define _IO_BIT_E3      3
#define _IO_PORT_REG_E4 PORTE
#define _IO_DDR_REG_E4  DDRE
#define _IO_PIN_REG_E4  PINE
#define _IO_BIT_E4      4
#define _IO_PORT_REG_E5 PORTE
#define _IO_DDR_REG_E5  DDRE
#define _IO_PIN_REG_E5  PINE
#define _IO_BIT_E5      5
#define _IO_PORT_REG_E6 PORTE
#define _IO_DDR_REG_E6  DDRE
#define _IO_PIN_REG_E6  PINE
#define _IO_BIT_E6      6
#define _IO_PORT_REG_E7 PORTE
#define _IO_DDR_REG_E7  DDRE
#define _IO_PIN_REG_E7  PINE
#define _IO_BIT_E7      7
#define _IO_PORT_REG_F0 PORTF
#define _IO_DDR_REG_F0  DDRF
#define _IO_PIN_REG_F0  PINF
#define _IO_BIT_F0      0
#define _IO_PORT_REG_F1 PORTF
#define _IO_DDR_REG_F1  DDRF
#define _IO_PIN_REG_F1  PINF
#define _IO_BIT_F1      1
#define _IO_PORT_REG_F2 PORTF
#define _IO_DDR_REG_F2  DDRF
#define _IO_PIN_REG_F2  PINF
#define _IO_BIT_F2      2
#define _IO_PORT_REG_F3 PORTF
#define _IO_DDR_REG_F3  DDRF
#define _IO_PIN_REG_F3  PINF
#define _IO_BIT_F3      3
#define _IO_PORT_REG_F4 PORTF
#define _IO_DDR_REG_F4  DDRF
#define _IO_PIN_REG_F4  PINF
#define _IO_BIT_F4      4
#define _IO_PORT_REG_F5 PORTF
#define _IO_DDR_REG_F5  DDRF
#define _IO_PIN_REG_F5  PINF
#define _IO_BIT_F5      5
#define _IO_PORT_REG_F6 PORTF
#define _IO_DDR_REG_F6  DDRF
#define _IO_PIN_REG_F6  PINF
#define _IO_BIT_F6      6
#define _IO_PORT_REG_F7 PORTF
#define _IO_DDR_REG_F7  DDRF
#define _IO_PIN_REG_F7  PINF
#define _IO_BIT_F7      7
#define _IO_PORT_REG_G0 PORTG
#define _IO_DDR_REG_G0  DDRG
#define _IO_PIN_REG_G0  PING
#define _IO_BIT_G0      0
#define _IO_PORT_REG_G1 PORTG
#define _IO_DDR_REG_G1  DDRG
#define _IO_PIN_REG_G1  PING
#define _IO_BIT_G1      1
#define _IO_PORT_REG_G2 PORTG
#define _IO_DDR_REG_G2  DDRG
#define _IO_PIN_REG_G2  PING
#define _IO_BIT_G2      2
#define _IO_PORT_REG_G3 PORTG
#define _IO_DDR_REG_G3  DDRG
#define _IO_PIN_REG_G3  PING
#define _IO_BIT_G3      3
#define _IO_PORT_REG_G4 PORTG
#define _IO_DDR_REG_G4  DDRG
#define _IO_PIN_REG_G4  PING
#define _IO_BIT_G4      4
#define _IO_PORT_REG_G5 PORTG
#define _IO_DDR_REG_G5  DDRG
#define _IO_PIN_REG_G5  PING
#define _IO_BIT_G5      5
#define _IO_PORT_REG_G6 PORTG
#define _IO_DDR_REG_G6  DDRG
#define _IO_PIN_REG_G6  PING
#define _IO_BIT_G6      6
#define _IO_PORT_REG_G7 PORTG
#define _IO_DDR_REG_G7  DDRG
#define _IO_PIN_REG_G7  PING
#define _IO_BIT_G7      7
#define _IO_PORT_REG_H0 PORTH
#define _IO_DDR_REG_H0  DDRH
#define _IO_PIN_REG_H0  PINH
#define _IO_BIT_H0      0
#define _IO_PORT_REG_H1 PORTH
#define _IO_DDR_REG_H1  DDRH
#define _IO_PIN_REG_H1  PINH
#define _IO_BIT_H1      1
#define _IO_PORT_REG_H2 PORTH
#define _IO_DDR_REG_H2  DDRH
#define _IO_PIN_REG_H2  PINH
#define _IO_BIT_H2      2
#define _IO_PORT_REG_H3 PORTH
#define _IO_DDR_REG_H3  DDRH
#define _IO_PIN_REG_H3  PINH
#define _IO_BIT_H3      3
#define _IO_PORT_REG_H4 PORTH
#define _IO_DDR_REG_H4  DDRH
#define _IO_PIN_REG_H4  PINH
#define _IO_BIT_H4      4
#define _IO_PORT_REG_H5 PORTH
#define _IO_DDR_REG_H5  DDRH
#define _IO_PIN_REG_H5  PINH
#define _IO_BIT_H5      5
#define _IO_PORT_REG_H6 PORTH
#define _IO_DDR_REG_H6  DDRH
#define _IO_PIN_REG_H6  PINH
#define _IO_BIT_H6      6
#define _IO_PORT_REG_H7 PORTH
#define _IO_DDR_REG_H7  DDRH
#define _IO_PIN_REG_H7  PINH
#define _IO_BIT_H7      7
#define _IO_PORT_REG_J0 PORTJ
#define _IO_DDR_REG_J0  DDRJ
#define _IO_PIN_REG_J0  PINJ
#define _IO_BIT_J0      0
#define _IO_PORT_REG_J1 PORTJ
#define _IO_DDR_REG_J1  DDRJ
#define _IO_PIN_REG_J1  PINJ
#define _IO_BIT_J1      1
#define _IO_PORT_REG_J2 PORTJ
#define _IO_DDR_REG_J2  DDRJ
#define _IO_PIN_REG_J2  PINJ
#define _IO_BIT_J2      2
#define _IO_PORT_REG_J3 PORTJ
#define _IO_DDR_REG_J3  DDRJ
#define _IO_PIN_REG_J3  PINJ
#define _IO_BIT_J3      3
#define _IO_PORT_REG_J4 PORTJ
#define _IO_DDR_REG_J4  DDRJ
#define _IO_PIN_REG_J4  PINJ
#define _IO_BIT_J4      4
#define _IO_PORT_REG_J5 PORTJ
#define _IO_DDR_REG_J5  DDRJ
#define _IO_PIN_REG_J5  PINJ
#define _IO_BIT_J5      5
#define _IO_PORT_REG_J6 PORTJ
#define _IO_DDR_REG_J6  DDRJ
#define _IO_PIN_REG_J6  PINJ
#define _IO_BIT_J6      6
#define _IO_PORT_REG_J7 PORTJ
#define _IO_DDR_REG_J7  DDRJ
#define _IO_PIN_REG_J7  PINJ
#define _IO_BIT_J7      7
#define _IO_PORT_REG_K0 PORTK
#define _IO_DDR_REG_K0  DDRK
#define _IO_PIN_REG_K0  PINK
#define _IO_BIT_K0      0
#define _IO_PORT_REG_K1 PORTK
#define _IO_DDR_REG_K1  DDRK
#define _IO_PIN_REG_K1  PINK
#define _IO_BIT_K1      1
#define _IO_PORT_REG_K2 PORTK
#define _IO_DDR_REG_K2  DDRK
#define _IO_PIN_REG_K2  PINK
#define _IO_BIT_K2      2
#define _IO_PORT_REG_K3 PORTK
#define _IO_DDR_REG_K3  DDRK
#define _IO_PIN_REG_K3  PINK
#define _IO_BIT_K3      3
#define _IO_PORT_REG_K4 PORTK
#define _IO_DDR_REG_K4  DDRK
#define _IO_PIN_REG_K4  PINK
#define _IO_BIT_K4      4
#define _IO_PORT_REG_K5 PORTK
#define _IO_DDR_REG_K5  DDRK
#define _IO_PIN_REG_K5  PINK
#define _IO_BIT_K5      5
#define _IO_PORT_REG_K6 PORTK
#define _IO_DDR_REG_K6  DDRK
#define _IO_PIN_REG_K6  PINK
#define _IO_BIT_K6      6
#define _IO_PORT_REG_K7 PORTK
#define _IO_DDR_REG_K7  DDRK
#define _IO_PIN_REG_K7  PINK
#define _IO_BIT_K7      7
#define _IO_PORT_REG_L0 PORTL
#define _IO_DDR_REG_L0  DDRL
#define _IO_PIN_REG_L0  PINL
#define _IO_BIT_L0      0
#define _IO_PORT_REG_L1 PORTL
#define _IO_DDR_REG_L1  DDRL
#define _IO_PIN_REG_L1  PINL
#define _IO_BIT_L1      1
#define _IO_PORT_REG_L2 PORTL
#define _IO_DDR_REG_L2  DDRL
#define _IO_PIN_REG_L2  PINL
#define _IO_BIT_L2      2
#define _IO_PORT_REG_L3 PORTL
#define _IO_DDR_REG_L3  DDRL
#define _IO_PIN_REG_L3  PINL
#define _IO_BIT_L3      3
#define _IO_PORT_REG_L4 PORTL
#define _IO_DDR_REG_L4  DDRL
#define _IO_PIN_REG_L4  PINL
#define _IO_BIT_L4      4
#define _IO_PORT_REG_L5 PORTL
#define _IO_DDR_REG_L5  DDRL
#define _IO_PIN_REG_L5  PINL
#define _IO_BIT_L5      5
#define _IO_PORT_REG_L6 PORTL
#define _IO_DDR_REG_L6  DDRL
#define _IO_PIN_REG_L6  PINL
#define _IO_BIT_L6      6
#define _IO_PORT_REG_L7 PORTL
#define _IO_DDR_REG_L7  DDRL
#define _IO_PIN_REG_L7  PINL
#define _IO_BIT_L7      7

#endif//GPIO_H
